<?php

return array(
  'eastlake-elkhart' => array(
    'title' => 'Eastlake Athletic Club Elkhart',
    'route' => 'eastlake-elkhart',
    'street' => '3400 Henke Rd.',
    'city' => 'Elkhart',
    'state' => 'IN',
    'zip' => '46514',
    'phone' => '574-264-0611',
  ),
  'eastlake-goshen' => array(
    'title' => 'Eastlake Athletic Club Goshen',
    'route' => 'eastlake-goshen',
    'street' => '1400 Fairfield Ave.',
    'city' => 'Goshen',
    'state' => 'IN',
    'zip' => '46526',
    'phone' => '574-533-2498',
  ),
  'eastlake-granger' => array(
    'title' => 'Eastlake 24 Granger (NEW)',
    'route' => 'eastlake-granger',
    'street' => '1202 East University Dr.',
    'city' => 'Granger',
    'state' => 'IN',
    'zip' => '46530',
    'phone' => '574-243-1823',
  ),
  'eastlake-17' => array(
    'title' => 'Eastlake 24 Elkhart CR 17',
    'route' => 'eastlake-17',
    'street' => '5150 Verdant Dr.',
    'city' => 'Elkhart',
    'state' => 'IN',
    'zip' => '46516',
    'phone' => '574-293-6899',
  ),
  'eastlake-middlebury' => array(
    'title' => 'Eastlake 24 Middlebury',
    'route' => 'eastlake-middlebury',
    'street' => '304 North Main St.',
    'city' => 'Middlebury',
    'state' => 'IN',
    'zip' => '46540',
    'phone' => '574-821-1560',
  ),
  'eastlake-northpointe' => array(
    'title' => 'Eastlake 24 Northpointe',
    'route' => 'eastlake-northpointe',
    'street' => '3130 Northview Dr.',
    'city' => 'Elkhart',
    'state' => 'IN',
    'zip' => '46514',
    'phone' => '574-266-8791',
  ),
  'eastlake-syracuse' => array(
    'title' => 'Eastlake 24 Syracuse',
    'route' => 'eastlake-syracuse',
    'street' => '734 South Huntington',
    'city' => 'Syracuse',
    'state' => 'IN',
    'zip' => '46567',
    'phone' => '574-337-1061',
  ),
  'eastlake-nappanee' => array(
    'title' => 'Eastlake 24 Nappanee',
    'route' => 'eastlake-nappanee',
    'street' => '1530 E Market St.',
    'city' => 'Nappanee',
    'state' => 'IN',
    'zip' => '46550',
    'phone' => '574-773-2643',
  )
);
